version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    volumes:
      - augie_cs_discord_bot_mongo_db:/data/db
        

  augie_cs_discord_bot:
    build: .
    image: docker.pkg.github.com/noah-witt/augiecsdiscordbot:0.1
    restart: always
    ports:
      - 127.0.0.1:8484:8080
    env_file:
      - example.env
      - .env
    links:
      - "mongo:db"
volumes:
  augie_cs_discord_bot_mongo_db: