version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    volumes:
      - augie_cs_discord_bot_mongo_db:/data/db
        

  augie_cs_discord_bot:
    build: .
    restart: always
    ports:
      - 127.0.0.1:8484:8080
    environment:
      - MONGO=mongodb://db:27017/results2020
      - discordLogin=<Fill in Discord Login>
      - discordChannelId=<Fill In Discord Channel Id>
      - TZ=America/Chicago
      - enableWeb=true
    links:
      - "mongo:db"
volumes:
  augie_cs_discord_bot_mongo_db: